Update ver. 0.4 to the specification
decentralized-identity/trustdidweb pull request #108
Opened 2024-09-24 22:02 UTC by swcurran

Signed-off-by: Stephen Curran <swcurran@gmail.com>

2024-09-24 22:07 UTC, swcurran commented
An update to the specification as per #106.

Note that the names of the items in the DID Log Entry object remain long form -- `versionId`, `versionTime`, `parameters`, `state` and `proof`.  There was some discussion of shortening them, but I plan to do that in a subsequent commit once we can have a discussion of the names to use.  Changing them from the current names to shorter versions will be easier from this point.

To be discussed at the 2024.09.26 did:tdw meeting -- [agenda here](https://hackmd.io/k4cIK9vQSlaeg2pdHE51IQ).

Feedback ahead of the meeting welcome -- anything unexpected in this?

2024-09-25 06:41 UTC, martipos commented on spec/version.md
> +  - Changes the data format of the [[ref: DID log entries]] from an array to an object. The [[ref: DID Log]] remains in the [[ref: JSON Lines]] format.
```suggestion
  - Changes the data format of the [[ref: DID log entries]] from an array to an object. The [[ref: DID Log]] remains in the [[ref: JSON Lines]] format.
  - Change the data format of the Data Integrity Proof from an array to an object
```

2024-09-26 23:40 UTC, swcurran commented
I've now updated the examples, per the implementation from the Python version.  In theory, this is now complete.

2024-09-27 14:14 UTC, martipos reviewed
Wording changes

- Removed my previous change that the Integrity Proof is a JSON Object, based on yesterdays discussion outcome (it will remain an array/set)
- replaced 'item'/'s' with 'property'/'ies' as we agreed to change the DID log entry data format  from array to JSON object

Signed-off-by: martipos <176692840+martipos@users.noreply.github.com>

2024-09-27 18:02 UTC, swcurran commented on spec/specification.md
> +`{ "versionId": "", "versionTime": "", "parameters": {}, "state": {}, "proof" : {} }`
Fixed

2024-09-27 18:02 UTC, swcurran commented on spec/specification.md
> +5. The JSON object `proof` is a [[ref: Data Integrity]] proof calculated across
Fixed

2024-09-27 18:02 UTC, swcurran commented on spec/specification.md
> +   collected and added to the [[ref: Data Integrity]] proof item. See the [DID
Fixed

2024-09-27 18:02 UTC, swcurran commented on spec/specification.md
> +4. Remove the [[ref: data integrity]] proof item from the [[ref: DID log entry]].
Fixed

2024-09-27 18:03 UTC, swcurran commented on spec/specification.md
> +`proof` item signed by a key **authorized** to control (create, update, deactivate) the
Fixed

2024-09-27 18:03 UTC, swcurran commented on spec/version.md
> +  - Change the data format of the Data Integrity Proof from an array to an object
Removed

2024-09-27 18:04 UTC, swcurran commented on spec/overview.md
> +3. Each [[ref: DID log entry]] is a JSON object containing the following items:
Fixed

2024-09-27 18:05 UTC, swcurran commented on spec/specification.md
> +Each entry is a JSON object consisting of the following items.
Fixed

2024-09-27 18:05 UTC, swcurran commented on spec/specification.md
> +   items that will be in the published [[ref: DID log entry]], but with some
Fixed

2024-09-27 18:05 UTC, swcurran commented on spec/specification.md
> +   without the `proof` item.
Fixed

2024-09-27 18:06 UTC, swcurran commented on spec/specification.md
> +   3. The value of the `parameters` item must be a JSON object defined at the
Fixed

2024-09-27 18:07 UTC, swcurran commented on spec/specification.md
> +      discretion of the [[ref: DID Controller]]. The items in the object
Fixed

2024-09-27 18:07 UTC, swcurran commented on spec/specification.md
> +   4. The value of the `state` item **MUST** be the initial [[ref: DIDDoc]] as
Fixed

2024-09-27 18:07 UTC, swcurran commented on spec/specification.md
> +   be generated using an authorized key in the required `updateKeys` item in the
Fixed

2024-09-27 18:08 UTC, swcurran commented on spec/specification.md
> +are each a JSON object with the following items:
Fixed

2024-09-27 18:09 UTC, swcurran commented on spec/specification.md
>     in the `parameters` item **MUST** match a hash in
Fixed

2024-09-27 18:10 UTC, swcurran commented on spec/specification.md
> +2. Define the [[ref: parameters]] JSON object to include the items that affect the evolution of the
Fixed

2024-09-27 18:10 UTC, swcurran commented on spec/specification.md
> +3. Generate a preliminary [[ref: DID log entry]] JSON object containing the following JSON items:
Fixed

2024-09-27 18:10 UTC, swcurran commented on spec/specification.md
>  5. Replace the value of the `versionId` item in the preliminary [[ref: DID Log
Fixed

2024-09-27 18:11 UTC, swcurran commented on spec/specification.md
> +8. The proof JSON object **MUST** be added as the value of the `proof` item in the [[ref: log entry]].
Fixed

2024-09-27 18:11 UTC, swcurran commented on spec/specification.md
>  DID log entry]] [[ref: parameters]] the item `"deactivated": true`. A [[ref: DID
Fixed

2024-09-27 18:12 UTC, swcurran commented on spec/specification.md
>  item `"deactivated": true` **MUST** return in the [[ref: DIDDoc]] Metadata the JSON item
Fixed

2024-09-27 18:12 UTC, swcurran commented on spec/specification.md
> +4. Remove the [[ref: data integrity]] proof item from the [[ref: DID log entry]].
Fixed

2024-09-27 18:13 UTC, swcurran commented on spec/specification.md
>  5. Replace the `versionId` item's value with the literal `"{SCID}"`.
Fixed

2024-09-27 18:14 UTC, swcurran commented on spec/specification.md
>  `entryHash` (first item) is the [[ref: SCID]] of the DID.
Fixed

2024-09-27 18:14 UTC, swcurran commented on spec/specification.md
>     `method` [[ref: parameters]] item set in the current or most recent prior [[ref: log entry]].
Fixed

2024-09-27 18:16 UTC, swcurran commented on spec/specification.md
>    inserts the [[ref: witnesses]]'s proofs into the array of proofs that are the last item in
Fixed — adjusted slightly.

2024-09-27 18:32 UTC, swcurran commented
Applied all the changes noted by @martipos and then removed the remaining instances of “item” used in the specification and related files.  I had thought that was the right term in JSON.  I’ve been using it for a while in many places, so I have now retrained myself! :-)

2024-09-28 04:47 UTC, swcurran commented
Added to the specification that the `versionTime` timestamp MUST be UTC time zone — per the suggestion in #112.

2024-10-02 14:04 UTC, brianorwhatever approved these changes

2024-10-02 16:51 UTC, PatStLouis requested changes
Overall great readability improvements and update. Added a few change request for consistency.

2024-10-02 16:51 UTC, PatStLouis commented on spec/overview.md
>      3. A set of `parameters` that impact the processing of the current and
```suggestion
    3. `parameters` -- a set of parameters that impact the processing of the current and
```

2024-10-02 16:51 UTC, PatStLouis commented on spec/overview.md
> +    4. The `state`, the new version of the [[ref: DIDDoc]].
```suggestion
    4. `state` -- the new version of the [[ref: DIDDoc]].
```

2024-10-02 16:51 UTC, PatStLouis commented on spec/overview.md
> +    5. A [[ref: Data Integrity]] (DI) proof across the entry, signed by a [[ref:
```suggestion
    5. `proof` -- a [[ref: Data Integrity]] (DI) proof across the entry, signed by a [[ref:
```

2024-10-02 17:51 UTC, PatStLouis approved these changes

2024-10-02 17:53 UTC, merged